- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - apt: name=unzip state=present
      when: allinone is defined and allinone

- hosts: guests:extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - name: create image data
      tags: userdata
      ansible.builtin.unarchive: src=/home/isucon/private_isu/seed/images.zip dest=/home/isucon/private_isu/seed/images remote_src=yes  
      when: allinone is defined and allinone
